openapi: 3.0.0
info:
  title: Church Management API
  description: API documentation for the Church Management system.
  version: 1.0.0
servers:
    - url: http://localhost/api
      description: Local server

paths:
    /update.php:
      post:
        summary: Update a member
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  first_name:
                    type: string
                  last_name:
                    type: string
                  email:
                    type: string
                  phone:
                    type: string
                  address:
                    type: string
                  status:
                    type: string
                  church_id:
                    type: integer
                  cgroup_id:
                    type: integer
                  next_of_kin:
                    type: string
                  number_of_kids:
                    type: integer
        responses:
          '200':
            description: Member was updated
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                    member:
                      type: object
                      properties:
                        id:
                          type: integer
                        first_name:
                          type: string
                        last_name:
                          type: string
                        email:
                          type: string
                        phone:
                          type: string
                        address:
                          type: string
                        status:
                          type: string
                        church_id:
                          type: integer
                        cgroup_id:
                          type: integer
                        next_of_kin:
                          type: string
                        member_number:
                          type: string
                        number_of_kids:
                          type: integer
          '400':
            description: Data is incomplete
          '503':
            description: Unable to update member

    /register.php:
      post:
        summary: Register a new user
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                  password:
                    type: string
                  firstname:
                    type: string
                  lastname:
                    type: string
                  role:
                    type: string
        responses:
          '201':
            description: User was created
          '400':
            description: Data is incomplete
          '503':
            description: Unable to create user

    /login.php:
      post:
        summary: User login
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                  password:
                    type: string
        responses:
          '200':
            description: Login successful
          '400':
            description: Data is incomplete
          '401':
            description: Invalid email or password

    /update_user_role.php:
      post:
        summary: Update user role
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  role:
                    type: string
        responses:
          '200':
            description: User role was updated
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    success:
                      type: boolean
          '400':
            description: Data is incomplete
          '503':
            description: Unable to update user role